name: nAlpine

services:
  nalpine:
    container_name: nalpine
    image: nalpine:latest
    pull_policy: never
    network_mode: host
    build: .
    volumes:
      - /home/eyal/Downloads/media:/media/media
    environment:
      - SERVER_PORT=8202
    privileged: true
    restart: unless-stopped