services:
  nalpine:
    image: nalpine:latest
    container_name: nalpine
    network_mode: host
    build: .
    privileged: true
    volumes:
      - /home/eyal/Downloads/media:/media/media    
    environment:
      - SERVER_PORT=8202
    restart: unless-stopped